/*
 * IriusRisk API
 * Products API
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.Group;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse201;
import io.swagger.client.model.JsonData1;
import io.swagger.client.model.JsonData13;
import io.swagger.client.model.JsonData14;
import io.swagger.client.model.JsonData2;
import io.swagger.client.model.JsonData3;
import io.swagger.client.model.JsonData4;
import io.swagger.client.model.ProductShortGroups;
import io.swagger.client.model.User;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GroupsApi
 */
@Ignore
public class GroupsApiTest {

    private final GroupsApi api = new GroupsApi();

    
    /**
     * Gets a list of all Groups
     *
     * Gets a list of all user&#39;s groups. Conditions to be able to perform the action:    - To have the permission **ALL_USERS_UPDATE** granted. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsGetTest() throws ApiException {
        String apiToken = null;
        List<Group> response = api.groupsGet(apiToken);

        // TODO: test validations
    }
    
    /**
     * Deletes a users group
     *
     * Deletes a users group. Conditions to be able to perform the action:    - To have the permission **ALL_USERS_UPDATE** granted. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsGroupRefDeleteTest() throws ApiException {
        String apiToken = null;
        String groupRef = null;
        api.groupsGroupRefDelete(apiToken, groupRef);

        // TODO: test validations
    }
    
    /**
     * Gets the group details.
     *
     * Returns the group details for the requested group. Conditions to be able to perform the action:    - If the caller has the PRODUCTS_LIST_ALL permission then all groups can be queried without restriction.    - Without the PRODUCTS_LIST_ALL permission, the call will only return the group if the caller belongs to that group. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsGroupRefGetTest() throws ApiException {
        String apiToken = null;
        String groupRef = null;
        List<Group> response = api.groupsGroupRefGet(apiToken, groupRef);

        // TODO: test validations
    }
    
    /**
     * Update a users group
     *
     * Updates a users group. Conditions to be able to perform the action:    - To have the permission **ALL_USERS_UPDATE** granted. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsGroupRefPutTest() throws ApiException {
        String apiToken = null;
        String groupRef = null;
        JsonData2 jsonData = null;
        Group response = api.groupsGroupRefPut(apiToken, groupRef, jsonData);

        // TODO: test validations
    }
    
    /**
     * Unassign a list of users from a group
     *
     * Unassign a list of users from a group. Conditions to be able to perform the action:  - To have the permission **ALL_USERS_UPDATE** granted, or  - To have the permission **MANAGE_USERS_BU** granted. With this permission you will be able to unassign users from a group, **if you belong to this group**. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsGroupUsersDeleteTest() throws ApiException {
        String apiToken = null;
        String group = null;
        JsonData4 jsonData = null;
        api.groupsGroupUsersDelete(apiToken, group, jsonData);

        // TODO: test validations
    }
    
    /**
     * List users from a group
     *
     * List users who belongs to a group. Conditions to be able to perform the action:  - To have the permission **ALL_USERS_UPDATE** granted, or  - To have the permission **MANAGE_USERS_BU** granted. With this permission you will be able to list users of a group, **if you belong to this group**. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsGroupUsersGetTest() throws ApiException {
        String apiToken = null;
        String group = null;
        List<User> response = api.groupsGroupUsersGet(apiToken, group);

        // TODO: test validations
    }
    
    /**
     * Assigns users to a group
     *
     * Assigns users to a group. Conditions to be able to perform the action:  - To have the permission **ALL_USERS_UPDATE** granted, or  - To have the permission **MANAGE_USERS_BU** granted. With this permission you will be able to assign users to a group, **if you belong to this group**. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsGroupUsersPutTest() throws ApiException {
        String apiToken = null;
        String group = null;
        JsonData3 jsonData = null;
        InlineResponse201 response = api.groupsGroupUsersPut(apiToken, group, jsonData);

        // TODO: test validations
    }
    
    /**
     * Removes a user from a group
     *
     * Unassign a user from a group. Conditions to be able to perform the action:  - To have the permission **ALL_USERS_UPDATE** granted, or  - To have the permission **MANAGE_USERS_BU** granted. With this permission you will be able to unassign user from a group, **if you belong to this group**. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsGroupUsersUserDeleteTest() throws ApiException {
        String apiToken = null;
        String group = null;
        String user = null;
        api.groupsGroupUsersUserDelete(apiToken, group, user);

        // TODO: test validations
    }
    
    /**
     * Creates a new user group
     *
     * Creates a new user group. Conditions to be able to perform the action:    - To have the permission **ALL_USERS_UPDATE** granted. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsPostTest() throws ApiException {
        String apiToken = null;
        JsonData1 jsonData = null;
        Group response = api.groupsPost(apiToken, jsonData);

        // TODO: test validations
    }
    
    /**
     * Unassigns a list of user groups from a product.
     *
     * Unassigns a list of user groups from a product. Conditions to be able to perform the action:   - To have the permission **PRODUCT_UPDATE** granted. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productsRefGroupsDeleteTest() throws ApiException {
        String apiToken = null;
        String ref = null;
        JsonData14 jsonData = null;
        InlineResponse200 response = api.productsRefGroupsDelete(apiToken, ref, jsonData);

        // TODO: test validations
    }
    
    /**
     * List all groups assigned to a product
     *
     * List all groups assigned to a product.     Conditions to be able to perform the action:         - If the caller has the PRODUCTS_LIST_ALL permission then all products can be queried without restriction.         - Without the PRODUCTS_LIST_ALL permission, the call will only return the groups if the caller belongs to that product. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productsRefGroupsGetTest() throws ApiException {
        String apiToken = null;
        String ref = null;
        List<String> response = api.productsRefGroupsGet(apiToken, ref);

        // TODO: test validations
    }
    
    /**
     * Assigns groups of users to a product.
     *
     * Assigns groups of users to a product. Conditions to be able to perform the action:   - To have the permission **PRODUCT_UPDATE** granted. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productsRefGroupsPutTest() throws ApiException {
        String apiToken = null;
        String ref = null;
        JsonData13 jsonData = null;
        ProductShortGroups response = api.productsRefGroupsPut(apiToken, ref, jsonData);

        // TODO: test validations
    }
    
}
